# Generated by Django 5.0.6 on 2024-05-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='trxid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(choices=[('CSE 1', 'CSE 1'), ('CSE 2', 'CSE 2'), ('CSE 3', 'CSE 3'), ('CSE 4', 'CSE 4'), ('CSE 5', 'CSE 5'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2'), ('CSE 2', 'CSE 2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
