# Generated by Django 5.0.6 on 2024-05-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0002_remove_user_transaction_id_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Registration',
        ),
    ]
