# Generated by Django 5.0.6 on 2024-05-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0004_alter_user_registration_num_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='num_guests',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='total_payment',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='trxid',
        ),
    ]
