# Generated by Django 5.0.6 on 2024-05-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0009_user_registration_batch_user_registration_num_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='batch',
        ),
    ]
