# Generated by Django 5.0.6 on 2024-05-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0012_remove_user_registration_trxid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='phonenumber',
        ),
    ]
