# Generated by Django 5.0.6 on 2024-05-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0014_alter_user_registration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
