# Generated by Django 5.0.6 on 2024-05-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0016_user_registration_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='batch',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
