# Generated by Django 5.0.6 on 2024-05-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0019_alter_user_registration_num_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='num_guests',
            field=models.IntegerField(default=0),
        ),
    ]
