# Generated by Django 5.0.6 on 2024-05-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0022_remove_user_registration_num_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='total_amount',
        ),
    ]
