# Generated by Django 5.0.6 on 2024-05-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0023_remove_user_registration_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
