# Generated by Django 5.0.6 on 2024-05-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0024_user_registration_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='batch',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
