# Generated by Django 5.0.6 on 2024-05-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0026_registrationforpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationforpage',
            old_name='confirm_password',
            new_name='confirmpassword',
        ),
        migrations.RenameField(
            model_name='registrationforpage',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
