# Generated by Django 5.0.6 on 2024-05-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0027_rename_confirm_password_registrationforpage_confirmpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationforpage',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='registrationforpage',
            name='password',
        ),
    ]
