# Generated by Django 5.0.6 on 2024-05-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0028_remove_registrationforpage_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationforpage',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
