# Generated by Django 5.0.6 on 2024-05-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0029_alter_registrationforpage_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationforpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registrationforpage',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='registrationforpage',
            name='username',
        ),
    ]
