# Generated by Django 5.0.6 on 2024-05-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0031_registrationforpage_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationforpage',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='registrationforpage',
            name='username',
        ),
    ]
