# Generated by Django 5.0.6 on 2024-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0032_rename_full_name_registrationforpage_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationforpage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
