# Generated by Django 5.0.6 on 2024-05-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0033_alter_registrationforpage_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationforpage',
            old_name='email',
            new_name='e_mail',
        ),
    ]
