# Generated by Django 5.0.6 on 2024-05-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0034_rename_email_registrationforpage_e_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationforpage',
            name='username',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
