# Generated by Django 5.0.6 on 2024-05-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0036_alter_registrationforpage_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationforpage',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
