# Generated by Django 5.0.6 on 2024-05-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0038_delete_registrationforpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
