# Generated by Django 5.0.6 on 2024-05-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration_app', '0042_group_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number_of_students', models.PositiveIntegerField()),
                ('cost_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
